{{ range .Values.applications }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Release.Name }}-{{ .name }}"
spec:
  selector:
    matchLabels:
      app: "{{ $.Release.Name }}-{{ .name }}"
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ $.Release.Name }}-{{ .name }}"
    spec:
      volumes: 
        - name: my-vol
          persistentVolumeClaim:
            claimName: myvol
      containers:
      - name: "{{ $.Release.Name }}-{{ .name }}"          
        volumeMounts:
          - name: my-vol
            mountPath: /tmp/shared-efs
        image: "{{ .image }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: "TCP"
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
        readinessProbe:
          httpGet:
            port: 8080
            path: /ride

{{ end }}
