# Replicas of each application
replicaCount: 1

# Domain the application will be served from
dnsName: kings-dominion-dev.apps.cluster-bpdzf.bpdzf.sandbox47.opentlc.com

applications:
  - name: kings-dominion-dev
    image: quay.io/rymiller/theme-park-api:kings-dominion
